function t121_setHeight(recid){var rec=$('#rec'+recid);var div=$("#youtubeiframe"+recid);var height=div.width()*0.5625;div.height(height);div.parent().height(height);var videoLazy=rec.find('.t-video-lazyload');var iframeLazy=videoLazy.find('iframe');if(videoLazy!=undefined){var heightLazy=videoLazy.width()*0.5625;videoLazy.height(heightLazy);iframeLazy.height(heightLazy)}}
function t142_checkSize(recid){var el=$("#rec"+recid).find(".t142__submit");if(el.length){var btnheight=el.height()+5;var textheight=el[0].scrollHeight;if(btnheight<textheight){var btntext=el.text();el.addClass("t142__submit-overflowed");el.html("<span class=\"t142__text\">"+btntext+"</span>")}}}
function t418_checkSize(recid){var el=$("#rec"+recid);var sizer=el.find('.t418__height');var height=sizer.height();var width=sizer.width();var ratio=width/height;var gallerywrapper=el.find(".t418__checksize");var gallerywidth=gallerywrapper.width();gallerywrapper.css({'height':((gallerywidth/ratio)+'px')});var maxwidth=el.find(".t418__height").width();var windowwidth=$(window).width();var value=windowwidth-80;if(maxwidth>windowwidth){el.find(".t418__item").css("max-width",value+"px");el.find(".t418__img").css("left","20px");el.find(".t418__img").css("right","20px")}else{el.find(".t418__item").css("max-width","");el.find(".t418__img").css("left","");el.find(".t418__img").css("right","")}}
function t418_init(recid){var el=$('#rec'+recid);var pos=0;var t418_doResize;var totalSlides=el.find('.t418__item').length;var sliderWidth=el.find('.t418__item').width();$(window).resize(function(){if(t418_doResize)clearTimeout(t418_doResize);t418_doResize=setTimeout(function(){sliderWidth=el.find('.t418__item').width();el.find('.t418__slidecontainer').width(sliderWidth*totalSlides);console.log(sliderWidth)},200)});el.find('.t418__slidecontainer').width(sliderWidth*totalSlides);el.find('.t418__next').click(function(){slideRight(recid)});el.find('.t418__previous').click(function(){slideLeft(recid)});function slideLeft(recid){var el=$('#rec'+recid);pos--;if(pos==-1){pos=totalSlides-1}
el.find('.t418__slidecontainer').css({transform:'translate(-'+(sliderWidth*pos)+'px, 0)'})
el.find('.t418__slidecontainer').css("transition-duration",".3s");if(window.lazy=='y'){t_lazyload_update()}}
function slideRight(recid){var el=$('#rec'+recid);pos++;if(pos==totalSlides){pos=0}
el.find('.t418__slidecontainer').css({transform:'translate(-'+(sliderWidth*pos)+'px, 0)'})
el.find('.t418__slidecontainer').css("transition-duration",".3s");if(window.lazy=='y'){t_lazyload_update()}}
var swipeOptions={triggerOnTouchEnd:!0,swipeStatus:swipeStatus,allowPageScroll:"vertical",threshold:75};el.find(".t418__slidecontainer").swipe(swipeOptions);el.find(".t418__slidecontainer").swipe({tap:function(event,target){slideRight(recid)}});function swipeStatus(event,phase,direction,distance){if(phase=="move"&&(direction=="left"||direction=="right")){var duration=0;if(direction=="left"){scrollImages((sliderWidth*pos)+distance,duration)}else if(direction=="right"){scrollImages((sliderWidth*pos)-distance,duration)}}else if(phase=="cancel"){scrollImages(sliderWidth*pos)}else if(phase=="end"){if(direction=="right"){slideLeft(recid)}else if(direction=="left"){slideRight(recid)}}}
function scrollImages(distance,duration){el.find(".t418__slidecontainer").css("transition-duration",(duration/1000).toFixed(1)+"s");var value=(distance<0?"":"-")+Math.abs(distance).toString();el.find(".t418__slidecontainer").css("transform","translate("+value+"px, 0)")}}
function t449_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t449").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");var hideoffset=el.attr("data-hideoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.hasClass('t449__beforeready')){el.finish();el.removeClass("t449__beforeready")}}else{el.stop();el.addClass("t449__beforeready")}}
if(hideoffset!=""){if(hideoffset.indexOf('vh')>-1){hideoffset=Math.floor((window.innerHeight*(parseInt(hideoffset)/100)))}
hideoffset=parseInt(hideoffset,10);if($(window).scrollTop()+$(window).height()>=$(document).height()-hideoffset){if(!el.hasClass('t449__beforeready')){el.finish();el.addClass("t449__beforeready")}}else{if(appearoffset!=""){if($(window).scrollTop()>=appearoffset){el.stop();el.removeClass("t449__beforeready")}}else{el.stop();el.removeClass("t449__beforeready")}}}})}}
function t452_scrollToTop(){$('html, body').animate({scrollTop:0},700)}
function t477_setHeight(recid){var el=$('#rec'+recid);el.find('.t-container').each(function(){var highestBox=0;$('.t477__col',this).each(function(){if($(this).height()>highestBox)highestBox=$(this).height()});$('.t477__textwrapper',this).css('height',highestBox);$('.t477__blockimg',this).css('height',highestBox)})}
function t480_setHeight(recid){var el=$('#rec'+recid);var sizer=el.find('.t480__sizer');var height=sizer.height();var width=sizer.width();var ratio=width/height;var imgwrapper=el.find(".t480__blockimg");var imgwidth=imgwrapper.width();if(height!=$(window).height()){imgwrapper.css({'height':((imgwidth/ratio)+'px')})}}
function t486_setHeight(recid){var el=$('#rec'+recid);var window_width=$(window).width();if(window_width>980){el.find('.t486__blockimg').css('height',el.find('.t486__blockimg').innerWidth());var textwrapper=el.find('.t486__textwrapper');var blockimg=el.find('.t486__imgcontainer');textwrapper.css('height',blockimg.innerHeight())}else{el.find('.t486__blockimg').css('height',el.find('.t486__blockimg').width());el.find('.t486__textwrapper').css('height','auto')}}
function t552_init(recid,ratio){var t552__el=$("#rec"+recid),t552__image=t552__el.find(".t552__blockimg:first");t552__setHeight(recid,t552__image,ratio);var t552__doResize;$(window).resize(function(){clearTimeout(t552__doResize);t552__doResize=setTimeout(function(){t552__setHeight(recid,t552__image,ratio)},200)})}
function t552__setHeight(recid,image,ratio){$("#rec"+recid+" .t552__blockimg").css("height",Math.round(image.innerWidth()*ratio))}
function t557_init(recid,snowtype){$('<img/>').attr('src','https://static.tildacdn.com/img/snowflakes_1.png').load(function(){$(this).remove()});$('<img/>').attr('src','https://static.tildacdn.com/img/snowflakes_2.png').load(function(){$(this).remove()});$('<img/>').attr('src','https://static.tildacdn.com/img/snowflakes_3.png').load(function(){$(this).remove();t557__addSnow(recid,snowtype)})}
function t557__addSnow(recid,snowtype){var el=$('#rec'+recid),t557_ids=el.find('.t557__snow-recid-holder').attr('data-snow-rec-ids').split(',');if(t557_ids!=""){t557_ids.forEach(function(rec_id,i,arr){var t557_zeroattr=$('#rec'+rec_id).attr('data-record-type');if(t557_zeroattr==396){var t557_wrappertype=" .t396__artboard"}else{var t557_wrappertype=" .t-cover"}
var t557_cover=document.querySelector('#rec'+rec_id+t557_wrappertype);if(t557_cover!=null){var t557_snow=document.createElement('div');t557_snow.className=snowtype;t557_cover.appendChild(t557_snow)}})}else{t557_cover=$('.t-cover').first();var t557_snow=document.createElement('div');t557_snow.className=snowtype;t557_cover.append(t557_snow)}
$('.'+snowtype).animate({"opacity":"1"},1000,function(){})}
function t602_init(recid){var t602_lastCall,t602_timeoutId,t602_interval=100;$(window).scroll(function(){var t602_now=new Date().getTime();if(t602_lastCall&&t602_now<(t602_lastCall+t602_interval)){clearTimeout(t602_timeoutId);t602_timeoutId=setTimeout(function(){t602_lastCall=t602_now;t602_setProgressBarWidth(recid)},t602_interval-(t602_now-t602_lastCall))}else{t602_lastCall=t602_now;t602_setProgressBarWidth(recid)}})}
function t602_setProgressBarWidth(recid){var t602_windowScrollTop=$(window).scrollTop(),t602_docHeight=$(document).height(),t602_winHeight=$(window).height();t602_scrollPercent=(t602_windowScrollTop/(t602_docHeight-t602_winHeight))*100;$(".t602__indicator").css('width',t602_scrollPercent+'%')}
function t670_init(recid){t670_imageHeight(recid);t670_show(recid);t670_hide(recid)}
function t670_show(recid){var el=$("#rec"+recid),play=el.find('.t670__play');play.click(function(){if($(this).attr('data-slider-video-type')=='youtube'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://www.youtube.com/embed/"+url+"?autoplay=1\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>")}
if($(this).attr('data-slider-video-type')=='vimeo'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://player.vimeo.com/video/"+url+"\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen></iframe>")}
$(this).next().css('z-index','3')})}
function t670_hide(recid){var el=$("#rec"+recid),body=el.find('.t670__frame');el.on('updateSlider',function(){body.html('').css('z-index','')})}
function t670_imageHeight(recid){var el=$("#rec"+recid);var image=el.find(".t670__separator");image.each(function(){var width=$(this).attr("data-slider-image-width");var height=$(this).attr("data-slider-image-height");var ratio=height/width;var padding=ratio*100;$(this).css("padding-bottom",padding+"%")})}
function t686_init(recid){setTimeout(function(){t686_setHeight(recid)},500);var t686__doResize;$(window).resize(function(){clearTimeout(t686__doResize);t686__doResize=setTimeout(function(){t686_setHeight(recid)},200)})}
function t686_setHeight(recid){var t686_el=$('#rec'+recid+' .t686'),t686_ratio=t686_el.attr('data-tile-ratio'),t686_ratioHeight=t686_el.find('.t686__col').width()*t686_ratio;t686_el.find('.t686__row').each(function(){var t686_largestHeight=0,t686_currow=$(this);$('.t686__table',this).each(function(){var t686_curCol=$(this),t686_curColHeight=t686_curCol.find(".t686__textwrapper").outerHeight();if($(this).find(".t686__cell").hasClass("t686__button-bottom")){t686_curColHeight+=t686_curCol.find(".t686__button-container").outerHeight()}
if(t686_curColHeight>t686_largestHeight){t686_largestHeight=t686_curColHeight}});if($(window).width()>=960){if(t686_largestHeight>t686_ratioHeight){$('.t686__table',this).css('height',t686_largestHeight)}
else{$('.t686__table',this).css('height',t686_ratioHeight)}
$('.t686__table',this).css('min-height','auto')}else{$('.t686__table',this).css('min-height',t686_ratioHeight);$('.t686__table',this).css('height','')}
if(t686_GetIEVersion()>0){var curRowHeight=$('.t686__table',this).css('height');$('.t686__bg',this).css('height',curRowHeight);$('.t686__overlay',this).css('height',curRowHeight)}})}
function t686_GetIEVersion(){var sAgent=window.navigator.userAgent;var Idx=sAgent.indexOf("MSIE");if(Idx>0){return parseInt(sAgent.substring(Idx+5,sAgent.indexOf(".",Idx)))}else{if(!!navigator.userAgent.match(/Trident\/7\./)){return 11}else{return 0}}}
function t694_init(recid){t694_setHeight(recid);var t694__doResize;$(window).resize(function(){clearTimeout(t694__doResize);t694__doResize=setTimeout(function(){t694_setHeight(recid)},200)})}
function t694_setHeight(recid){var t694_el=$('#rec'+recid+' .t694'),t694_ratio=t694_el.attr('data-tile-ratio'),t694_ratioHeight=t694_el.find('.t694__col').width()*t694_ratio;if($(window).width()>=768){t694_el.find('.t694__row').each(function(){var t694_largestHeight=0,t694_currow=$(this);$('.t694__table',this).each(function(){var t694_curCol=$(this),t694_curColHeight=t694_curCol.find(".t694__textwrapper").outerHeight();if($(this).find(".t694__cell").hasClass("t694__button-bottom")){t694_curColHeight+=t694_curCol.find(".t694__button-container").outerHeight()}
if(t694_curColHeight>t694_largestHeight){t694_largestHeight=t694_curColHeight}});if(t694_largestHeight>t694_ratioHeight){$('.t694__table',this).css('height',t694_largestHeight)}else{if($('.t694__table',this).css('height')!=''){$('.t694__table',this).css('height','')}}})}else{t694_el.find('.t694__table').css('height','')}}
function t814_init(recid){t814_setHeight(recid);$(window).bind('resize',t_throttle(function(){if(typeof window.noAdaptive!="undefined"&&window.noAdaptive==!0&&$isMobile){return}
t814_setHeight(recid)},200));$('.t814').bind('displayChanged',function(){t814_setHeight(recid)})}
function t814_setHeight(rec){el=$('#rec'+rec)
var imgWrapperHeight=el.find(".t814__blockimg").height();var blockTextWrapper=el.find(".t814__blocktext-wrapper");var textWrapper=el.find(".t814__blocktext");if($(window).width()>960){textWrapper.css('height',imgWrapperHeight);blockTextWrapper.css('height',textWrapper.outerHeight(!0))}else{blockTextWrapper.css('height','auto')}}
function t816_init(recid,padding){var rec=$('#rec'+recid);var el=rec.find('.t816');t816_setHeight(rec,padding);$(window).bind('resize',t_throttle(function(){if(typeof window.noAdaptive!="undefined"&&window.noAdaptive==!0&&$isMobile){return}
t816_setHeight(rec,padding)},200));$('.t816').bind('displayChanged',function(){t816_setHeight(rec,padding)})}
function t816_setHeight(rec,padding){var galleryContainer=$('.t816__container');var galleryRow=$('.t816__row:first-child');var colOffset=$('.t816__tile_offset');if(colOffset.length==0){return}
var containerOffset=colOffset.position().top-padding;if($(window).width()>=960){galleryContainer.css('padding-bottom',containerOffset)}}
function t827_init(recid){var rec=$('#rec'+recid);var grid=rec.find('.t827__grid');var sizer=rec.find('.t827__grid-sizer');var item=rec.find('.t827__grid-item');var images=rec.find('.t827__grid img');var overlay=rec.find('.t827__overlay');var startContainerWidth=rec.find('.t827__grid-sizer').width();t827_reverse(grid,item);images.load(function(){t827_initMasonry(rec,recid,grid);setTimeout(function(){t827_showOverlay(overlay,item)},500)});if(overlay.hasClass('t827__overlay_preview')){setTimeout(function(){t827_showOverlay(overlay,item)},1000)}
t827_initMasonry(rec,recid,grid);$(window).bind('resize',function(){if(typeof window.noAdaptive!="undefined"&&window.noAdaptive==!0&&$isMobile){return}
t827_calcColumnWidth(rec,startContainerWidth,grid,sizer,item)});$('.t827').bind('displayChanged',function(){t827_initMasonry(rec,recid,grid);t827_calcColumnWidth(rec,startContainerWidth,grid,sizer,item)});t827_calcColumnWidth(rec,startContainerWidth,grid,sizer,item)}
function t827_reverse(grid,item){if(grid.hasClass('t827__grid_reverse')){grid.append(function(){return $(this).children().get().reverse()})}}
function t827_initMasonry(rec,recid,grid){var $grid=grid;var gutterSizerWidth=rec.find('.t827__gutter-sizer').width();var gutterElement=rec.find('.t827__gutter-sizer').width()==40?39:'#rec'+recid+' .t827__gutter-sizer';$grid.imagesLoaded(function(){$grid.masonry({itemSelector:'#rec'+recid+' .t827__grid-item',columnWidth:'#rec'+recid+' .t827__grid-sizer',gutter:gutterElement,isFitWidth:!0})})}
function t827_showOverlay(overlay,item){if($(window).width()>=1024){overlay.css('display','block')}else{item.click(function(){if($(this).find('.t827__overlay').css('opacity')=='0'){overlay.css('opacity','0');$(this).find('.t827__overlay').css('opacity','1')}else{$(this).find('.t827__overlay').css('opacity','0')}})}}
function t827_calcColumnWidth(rec,startcontainerwidth,grid,sizer,item){var containerWidth=rec.find('.t827__container').width();var sizerWidth=rec.find('.t827__grid-sizer').width();var itemWidth=rec.find('.t827__grid-item').width();var gutterSizerWidth=rec.find('.t827__gutter-sizer').width()==40?39:rec.find('.t827__gutter-sizer').width();var columnAmount=Math.round(containerWidth/startcontainerwidth);var newSizerWidth=((containerWidth-gutterSizerWidth*(columnAmount-1))/columnAmount);if(containerWidth>=itemWidth){sizer.css('width',newSizerWidth);item.css('width',newSizerWidth)}else{grid.css('width','100%');sizer.css('width','100%');item.css('width','100%')}}
function t843_init(recid){var rec=$('#rec'+recid);var container=rec.find('.t843');t843_setHeight(rec);$(window).bind('resize',t_throttle(function(){if(typeof window.noAdaptive!="undefined"&&window.noAdaptive==!0&&$isMobile){return}
t843_setHeight(rec)},200));$('.t843').bind('displayChanged',function(){t843_setHeight(rec)});if(container.hasClass('t843__previewmode')){setInterval(function(){t843_setHeight(rec)},5000)}}
function t843_setHeight(rec){var image=rec.find('.t843__blockimg');image.each(function(){var width=$(this).attr('data-image-width');var height=$(this).attr('data-image-height');var ratio=height/width;var padding=ratio*100;$(this).css('padding-bottom',padding+'%')});if($(window).width()>960){var textwr=rec.find('.t843__textwrapper');var deskimg=rec.find('.t843__desktopimg');textwr.each(function(i){$(this).css('height',$(deskimg[i]).innerHeight())})}}
function t851_init(recid){var rec=$('#rec'+recid+' .t851');var doResize;setTimeout(function(){t851_setHeight(rec);t851_updateLazyLoad(recid)},500);$(window).resize(function(){clearTimeout(doResize);doResize=setTimeout(function(){t851_setHeight(rec)},200)});$('.t851').bind('displayChanged',function(){t851_setHeight(rec)});if(rec.hasClass('t851__previewmode')){setInterval(function(){t851_setHeight(rec)},5000)}}
function t851_setHeight(rec){var ratio=rec.attr('data-tile-ratio');var ratioHeight=rec.find('.t851__col').width()*ratio;rec.find('.t851__row').each(function(){var largestHeight=0;var currow=$(this);$('.t851__table',this).each(function(){var curCol=$(this);var curColHeight=curCol.find('.t851__textwrapper').outerHeight();if($(this).find('.t851__cell').hasClass('t851__button-bottom')){curColHeight+=curCol.find('.t851__button-container').outerHeight()}
if(curColHeight>largestHeight){largestHeight=curColHeight}});if($(window).width()>=960){if(largestHeight>ratioHeight){$('.t851__table',this).css('height',largestHeight)}
else{$('.t851__table',this).css('height',ratioHeight)}
$('.t851__table',this).css('min-height','auto')}else{$('.t851__table',this).css('min-height',ratioHeight);$('.t851__table',this).css('height','')}
if(t851_GetIEVersion()>0){var curRowHeight=$('.t851__table',this).css('height');$('.t851__bg',this).css('height',curRowHeight);$('.t851__overlay',this).css('height',curRowHeight)}})}
function t851_GetIEVersion(){var sAgent=window.navigator.userAgent;var Idx=sAgent.indexOf("MSIE");if(Idx>0){return parseInt(sAgent.substring(Idx+5,sAgent.indexOf(".",Idx)))}else{if(!!navigator.userAgent.match(/Trident\/7\./)){return 11}else{return 0}}}
function t851_updateLazyLoad(recid){var scrollContainer=$("#rec"+recid+" .t851__container_mobile-flex");var curMode=$(".t-records").attr("data-tilda-mode");if(scrollContainer.length&&curMode!="edit"&&curMode!="preview"){scrollContainer.bind('scroll',t_throttle(function(){t_lazyload_update()},500))}}